//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("BlogModel", "FK_Komentarze_Post", "Post", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Blog.Models.Post), "Komentarze", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Blog.Models.Komentarze), true)]
[assembly: EdmRelationshipAttribute("BlogModel", "FK_Tagi_Tagi", "Post", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(Blog.Models.Post), "Tagi", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(Blog.Models.Tagi), true)]

#endregion

namespace Blog.Models
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BlogEntities : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BlogEntities object using the connection string found in the 'BlogEntities' section of the application configuration file.
        /// </summary>
        public BlogEntities() : base("name=BlogEntities", "BlogEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BlogEntities object.
        /// </summary>
        public BlogEntities(string connectionString) : base(connectionString, "BlogEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BlogEntities object.
        /// </summary>
        public BlogEntities(EntityConnection connection) : base(connection, "BlogEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Komentarze> Komentarze
        {
            get
            {
                if ((_Komentarze == null))
                {
                    _Komentarze = base.CreateObjectSet<Komentarze>("Komentarze");
                }
                return _Komentarze;
            }
        }
        private ObjectSet<Komentarze> _Komentarze;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Post> Post
        {
            get
            {
                if ((_Post == null))
                {
                    _Post = base.CreateObjectSet<Post>("Post");
                }
                return _Post;
            }
        }
        private ObjectSet<Post> _Post;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagrams> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagrams>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagrams> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Tagi> Tagi
        {
            get
            {
                if ((_Tagi == null))
                {
                    _Tagi = base.CreateObjectSet<Tagi>("Tagi");
                }
                return _Tagi;
            }
        }
        private ObjectSet<Tagi> _Tagi;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Ustawienia> Ustawienia
        {
            get
            {
                if ((_Ustawienia == null))
                {
                    _Ustawienia = base.CreateObjectSet<Ustawienia>("Ustawienia");
                }
                return _Ustawienia;
            }
        }
        private ObjectSet<Ustawienia> _Ustawienia;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Komentarze EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToKomentarze(Komentarze komentarze)
        {
            base.AddObject("Komentarze", komentarze);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Post EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToPost(Post post)
        {
            base.AddObject("Post", post);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagrams sysdiagrams)
        {
            base.AddObject("sysdiagrams", sysdiagrams);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Tagi EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTagi(Tagi tagi)
        {
            base.AddObject("Tagi", tagi);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Ustawienia EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToUstawienia(Ustawienia ustawienia)
        {
            base.AddObject("Ustawienia", ustawienia);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BlogModel", Name="Komentarze")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Komentarze : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Komentarze object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="id_posta">Initial value of the id_posta property.</param>
        /// <param name="tresc">Initial value of the tresc property.</param>
        /// <param name="autor">Initial value of the autor property.</param>
        /// <param name="data_dodania">Initial value of the data_dodania property.</param>
        /// <param name="status">Initial value of the status property.</param>
        public static Komentarze CreateKomentarze(global::System.Int32 id, global::System.Int32 id_posta, global::System.String tresc, global::System.String autor, global::System.DateTime data_dodania, global::System.Int32 status)
        {
            Komentarze komentarze = new Komentarze();
            komentarze.id = id;
            komentarze.id_posta = id_posta;
            komentarze.tresc = tresc;
            komentarze.autor = autor;
            komentarze.data_dodania = data_dodania;
            komentarze.status = status;
            return komentarze;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_posta
        {
            get
            {
                return _id_posta;
            }
            set
            {
                Onid_postaChanging(value);
                ReportPropertyChanging("id_posta");
                _id_posta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_posta");
                Onid_postaChanged();
            }
        }
        private global::System.Int32 _id_posta;
        partial void Onid_postaChanging(global::System.Int32 value);
        partial void Onid_postaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tresc
        {
            get
            {
                return _tresc;
            }
            set
            {
                OntrescChanging(value);
                ReportPropertyChanging("tresc");
                _tresc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tresc");
                OntrescChanged();
            }
        }
        private global::System.String _tresc;
        partial void OntrescChanging(global::System.String value);
        partial void OntrescChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String autor
        {
            get
            {
                return _autor;
            }
            set
            {
                OnautorChanging(value);
                ReportPropertyChanging("autor");
                _autor = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("autor");
                OnautorChanged();
            }
        }
        private global::System.String _autor;
        partial void OnautorChanging(global::System.String value);
        partial void OnautorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime data_dodania
        {
            get
            {
                return _data_dodania;
            }
            set
            {
                Ondata_dodaniaChanging(value);
                ReportPropertyChanging("data_dodania");
                _data_dodania = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("data_dodania");
                Ondata_dodaniaChanged();
            }
        }
        private global::System.DateTime _data_dodania;
        partial void Ondata_dodaniaChanging(global::System.DateTime value);
        partial void Ondata_dodaniaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.Int32 _status;
        partial void OnstatusChanging(global::System.Int32 value);
        partial void OnstatusChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlogModel", "FK_Komentarze_Post", "Post")]
        public Post Post
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Post>("BlogModel.FK_Komentarze_Post", "Post").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Post>("BlogModel.FK_Komentarze_Post", "Post").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Post> PostReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Post>("BlogModel.FK_Komentarze_Post", "Post");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Post>("BlogModel.FK_Komentarze_Post", "Post", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BlogModel", Name="Post")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Post : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Post object.
        /// </summary>
        /// <param name="id">Initial value of the id property.</param>
        /// <param name="data_dodania">Initial value of the data_dodania property.</param>
        /// <param name="tytul">Initial value of the tytul property.</param>
        /// <param name="tresc">Initial value of the tresc property.</param>
        /// <param name="status">Initial value of the status property.</param>
        public static Post CreatePost(global::System.Int32 id, global::System.DateTime data_dodania, global::System.String tytul, global::System.String tresc, global::System.Int32 status)
        {
            Post post = new Post();
            post.id = id;
            post.data_dodania = data_dodania;
            post.tytul = tytul;
            post.tresc = tresc;
            post.status = status;
            return post;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.DateTime data_dodania
        {
            get
            {
                return _data_dodania;
            }
            set
            {
                Ondata_dodaniaChanging(value);
                ReportPropertyChanging("data_dodania");
                _data_dodania = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("data_dodania");
                Ondata_dodaniaChanged();
            }
        }
        private global::System.DateTime _data_dodania;
        partial void Ondata_dodaniaChanging(global::System.DateTime value);
        partial void Ondata_dodaniaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tytul
        {
            get
            {
                return _tytul;
            }
            set
            {
                OntytulChanging(value);
                ReportPropertyChanging("tytul");
                _tytul = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tytul");
                OntytulChanged();
            }
        }
        private global::System.String _tytul;
        partial void OntytulChanging(global::System.String value);
        partial void OntytulChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String tresc
        {
            get
            {
                return _tresc;
            }
            set
            {
                OntrescChanging(value);
                ReportPropertyChanging("tresc");
                _tresc = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("tresc");
                OntrescChanged();
            }
        }
        private global::System.String _tresc;
        partial void OntrescChanging(global::System.String value);
        partial void OntrescChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> data_modyfikacji
        {
            get
            {
                return _data_modyfikacji;
            }
            set
            {
                Ondata_modyfikacjiChanging(value);
                ReportPropertyChanging("data_modyfikacji");
                _data_modyfikacji = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("data_modyfikacji");
                Ondata_modyfikacjiChanged();
            }
        }
        private Nullable<global::System.DateTime> _data_modyfikacji;
        partial void Ondata_modyfikacjiChanging(Nullable<global::System.DateTime> value);
        partial void Ondata_modyfikacjiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 status
        {
            get
            {
                return _status;
            }
            set
            {
                OnstatusChanging(value);
                ReportPropertyChanging("status");
                _status = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("status");
                OnstatusChanged();
            }
        }
        private global::System.Int32 _status;
        partial void OnstatusChanging(global::System.Int32 value);
        partial void OnstatusChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlogModel", "FK_Komentarze_Post", "Komentarze")]
        public EntityCollection<Komentarze> Komentarze
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Komentarze>("BlogModel.FK_Komentarze_Post", "Komentarze");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Komentarze>("BlogModel.FK_Komentarze_Post", "Komentarze", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlogModel", "FK_Tagi_Tagi", "Tagi")]
        public EntityCollection<Tagi> Tagi
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Tagi>("BlogModel.FK_Tagi_Tagi", "Tagi");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Tagi>("BlogModel.FK_Tagi_Tagi", "Tagi", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BlogModel", Name="sysdiagrams")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagrams : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagrams object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagrams Createsysdiagrams(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagrams sysdiagrams = new sysdiagrams();
            sysdiagrams.name = name;
            sysdiagrams.principal_id = principal_id;
            sysdiagrams.diagram_id = diagram_id;
            return sysdiagrams;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BlogModel", Name="Tagi")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Tagi : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Tagi object.
        /// </summary>
        /// <param name="id_posta">Initial value of the id_posta property.</param>
        /// <param name="keywords">Initial value of the keywords property.</param>
        /// <param name="description">Initial value of the description property.</param>
        /// <param name="id">Initial value of the id property.</param>
        public static Tagi CreateTagi(global::System.Int32 id_posta, global::System.String keywords, global::System.String description, global::System.Int32 id)
        {
            Tagi tagi = new Tagi();
            tagi.id_posta = id_posta;
            tagi.keywords = keywords;
            tagi.description = description;
            tagi.id = id;
            return tagi;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id_posta
        {
            get
            {
                return _id_posta;
            }
            set
            {
                Onid_postaChanging(value);
                ReportPropertyChanging("id_posta");
                _id_posta = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("id_posta");
                Onid_postaChanged();
            }
        }
        private global::System.Int32 _id_posta;
        partial void Onid_postaChanging(global::System.Int32 value);
        partial void Onid_postaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String keywords
        {
            get
            {
                return _keywords;
            }
            set
            {
                OnkeywordsChanging(value);
                ReportPropertyChanging("keywords");
                _keywords = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("keywords");
                OnkeywordsChanged();
            }
        }
        private global::System.String _keywords;
        partial void OnkeywordsChanging(global::System.String value);
        partial void OnkeywordsChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String description
        {
            get
            {
                return _description;
            }
            set
            {
                OndescriptionChanging(value);
                ReportPropertyChanging("description");
                _description = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("description");
                OndescriptionChanged();
            }
        }
        private global::System.String _description;
        partial void OndescriptionChanging(global::System.String value);
        partial void OndescriptionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int32 _id;
        partial void OnidChanging(global::System.Int32 value);
        partial void OnidChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("BlogModel", "FK_Tagi_Tagi", "Post")]
        public Post Post
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Post>("BlogModel.FK_Tagi_Tagi", "Post").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Post>("BlogModel.FK_Tagi_Tagi", "Post").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Post> PostReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Post>("BlogModel.FK_Tagi_Tagi", "Post");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Post>("BlogModel.FK_Tagi_Tagi", "Post", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="BlogModel", Name="Ustawienia")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Ustawienia : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Ustawienia object.
        /// </summary>
        /// <param name="grupa">Initial value of the grupa property.</param>
        /// <param name="nazwa">Initial value of the nazwa property.</param>
        /// <param name="wartosc">Initial value of the wartosc property.</param>
        public static Ustawienia CreateUstawienia(global::System.String grupa, global::System.String nazwa, global::System.String wartosc)
        {
            Ustawienia ustawienia = new Ustawienia();
            ustawienia.grupa = grupa;
            ustawienia.nazwa = nazwa;
            ustawienia.wartosc = wartosc;
            return ustawienia;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String grupa
        {
            get
            {
                return _grupa;
            }
            set
            {
                if (_grupa != value)
                {
                    OngrupaChanging(value);
                    ReportPropertyChanging("grupa");
                    _grupa = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("grupa");
                    OngrupaChanged();
                }
            }
        }
        private global::System.String _grupa;
        partial void OngrupaChanging(global::System.String value);
        partial void OngrupaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String nazwa
        {
            get
            {
                return _nazwa;
            }
            set
            {
                if (_nazwa != value)
                {
                    OnnazwaChanging(value);
                    ReportPropertyChanging("nazwa");
                    _nazwa = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("nazwa");
                    OnnazwaChanged();
                }
            }
        }
        private global::System.String _nazwa;
        partial void OnnazwaChanging(global::System.String value);
        partial void OnnazwaChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String wartosc
        {
            get
            {
                return _wartosc;
            }
            set
            {
                if (_wartosc != value)
                {
                    OnwartoscChanging(value);
                    ReportPropertyChanging("wartosc");
                    _wartosc = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("wartosc");
                    OnwartoscChanged();
                }
            }
        }
        private global::System.String _wartosc;
        partial void OnwartoscChanging(global::System.String value);
        partial void OnwartoscChanged();

        #endregion
    
    }

    #endregion
    
}
